name: CI-jira
on:
  workflow_dispatch:

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn -B package -DskipTests --file raf3k/pom.xml

    - name: Run Maven tests
      run: |
        mvn test --file raf3k/pom.xml
      continue-on-error: true

    - name: Submit results to Xray
      env:
        JIRA_SERVER_URL: ${{ secrets.jira_server_url }}
        JIRA_USERNAME: ${{ secrets.jira_username }}
        JIRA_PASSWORD: ${{ secrets.jira_password }}
      run: 'curl -H "Content-Type: multipart/form-data" -u $JIRA_USERNAME:$JIRA_PASSWORD -F "file=@target/surefire-reports/testng-results.xml" "$JIRA_SERVER_URL/rest/raven/1.0/import/execution/junit?projectKey=SCRUM"'
