name: Java CI with Maven

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package -DskipTests --file raf3k/pom.xml

    - name: Get commit SHA
      id: get_commit_sha
      run: echo "::set-output name=commit_sha::$(git rev-parse --short=7 HEAD)"

      # Example: Publish to GitHub Releases
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_commit_sha.outputs.commit_sha }}
        release_name: Release ${{ steps.get_commit_sha.outputs.commit_sha }}
        body: |
          Changes in this release:
          - Some changes
        draft: false
        prerelease: false

    - name: Upload Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: raf3k/target/raf3k-1.0-SNAPSHOT.jar
        asset_name: raf3k-1.0-SNAPSHOT.jar
        asset_content_type: application/java-archive

    - name: Upload results to Xray
      id: upload-result-xray
      env:
        JIRA_SERVER_URL: ${{ secrets.jira_server_url }}
        JIRA_USERNAME: ${{ secrets.jira_username }}
        JIRA_PASSWORD: ${{ secrets.jira_password }}
      run: 'curl -H "Content-Type: multipart/form-data" -u $JIRA_USERNAME:$JIRA_PASSWORD -F "file=@target/surefire-reports/TEST-com.xpand.java.CalcTest.xml" "$JIRA_SERVER_URL/rest/raven/1.0/import/execution/junit?projectKey=CALC"'
